Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2020-03, with the labels that each got.

#444 Update debugger library
  source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
  source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj
  source/VisualStudio.Extension-2019/app.config
  source/VisualStudio.Extension-2019/packages.config
  source/VisualStudio.Extension-2019/version.json
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
  source/VisualStudio.Extension/VisualStudio.Extension.csproj
  source/VisualStudio.Extension/app.config
  source/VisualStudio.Extension/packages.config
  source/VisualStudio.Extension/version.json
Labels: Area: VS-extension, Type: dependencies, VS2017, VS2019

#459 Fix assembly reference on network config dialog
  source/VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml
Labels: CI: Publish Release, Type: bug, VS2017, VS2019

#461 Fix project files not showing in dialog window when adding existing projects
  source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  source/VisualStudio.Extension/NanoFrameworkPackage.cs
Labels: Type: enhancement, VS2017, VS2019

#460 Fix deployment for solutions with with more than one shared project
  source/VisualStudio.Extension/Utilities/ReferenceCrawler.cs
Labels: Type: bug, VS2017, VS2019

#463 General improvements
  source/VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
  source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
  source/VisualStudio.Extension/NanoFrameworkPackage.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
Labels: Type: enhancement, VS2017, VS2019

#464 Update NuGets in VS2017
  source/Tools.BuildTasks/Tools.BuildTasks.csproj
  source/Tools.BuildTasks/packages.config
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/NetworkConfigurationDialog.xaml.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  source/VisualStudio.Extension/VisualStudio.Extension.csproj
  source/VisualStudio.Extension/app.config
  source/VisualStudio.Extension/packages.config
  source/VisualStudio.Extension/version.json
  source/nanoFramework.Tools.VisualStudio.sln
  source/readme.md
Labels: Type: dependencies, VS2017

#462 Fix deploy project from context menu.
  source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
Labels: Type: enhancement, VS2017, VS2019

#466 Code cleanup
  source/Tools.BuildTasks/GenerateNanoResourceTask.cs
  source/VisualStudio.Extension-2019/VisualStudio.Extension.csproj
  source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
  source/VisualStudio.Extension/DeployProvider/DeployState.cs
  source/VisualStudio.Extension/NanoFrameworkPackage.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml.cs
  source/VisualStudio.Extension/VisualStudio.Extension.csproj
Labels: Type: enhancement, VS2017, VS2019
