Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2020-05, with the labels that each got.

#479 Various fixes
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
  source/VisualStudio.Extension/ToolWindow.DeviceExplorer/ViewModel/DeviceExplorerViewModel.cs
Labels: Type: bug, VS2017, VS2019

#481 Improve debug session start sequence
  source/VisualStudio.Extension-2019/version.json
  source/VisualStudio.Extension/CorDebug/CorDebugProcess.cs
  source/VisualStudio.Extension/MessageCentre/MessageCentre.cs
  source/VisualStudio.Extension/version.json
Labels: Breaking-Change, CI: Publish Release, Type: enhancement, VS2017, VS2019

#482 Remove output of deployment exception
  source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
Labels: Type: enhancement, VS2017, VS2019

#483 Improve GetFieldValue
  source/VisualStudio.Extension/CorDebug/CorDebugValue.cs
Labels: Type: enhancement, VS2017, VS2019

#484 Improve deployment error message
  source/VisualStudio.Extension/DeployProvider/DeployProvider.cs
Labels: Type: enhancement, VS2017, VS2019

#488 Add resource support for Bitmaps and correct Font namespace
  source/Tools.BuildTasks/ProcessResourceFiles.cs
Labels: Type: bug, VS2017, VS2019
