Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2021-11, with the labels that each got.

#657 Improvements in Device Explorer
  VisualStudio.Extension-2019/Resources/NanoFramework.xaml
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
  VisualStudio.Extension/Resources/NanoFramework.xaml
  VisualStudio.Extension/ToolWindow.DeviceExplorer/DeviceExplorerControl.xaml
Labels: Type: enhancement, VS2017, VS2019

#659 Remove unused changelog file
  CHANGELOG-VS2022.md
  CHANGELOG.md
Labels: Area: Config-and-Build

#660 Fix generator for binary resources
  Tools.BuildTasks-2017/ProcessResourceFiles.cs
Labels: Type: bug, Breaking-Change, VS2019, VS2022

#661 Update several NuGets
  CSharp.AssemblyInfoTemplate/CSharp.AssemblyInfoTemplate.csproj
  CSharp.TestApplication/CS.TestApplication-vs2017.vstemplate
  CSharp.TestApplication/CS.TestApplication-vs2019.vstemplate
  CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate
  CSharp.TestApplication/NFUnitTest.nfproj
  NuGet.Config
  VisualStudio.Extension-2019/VisualStudio.Extension-vs2019.csproj
  VisualStudio.Extension-2019/packages.lock.json
  VisualStudio.Extension-2019/source.extension.vsixmanifest
  VisualStudio.Extension-2019/version.json
  VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
  VisualStudio.Extension-2022/packages.lock.json
  VisualStudio.Extension-2022/source.extension.vsixmanifest
  VisualStudio.Extension-2022/version.json
Labels: Type: dependencies, VS2019, VS2022

#662 Fix missing images for VS menu items
  VisualStudio.Extension-2022/NanoFrameworkPackage.cs
  VisualStudio.Extension-2022/NanoFrameworkPackage.vsct
  VisualStudio.Extension-2022/packages.lock.json
  VisualStudio.Extension-2022/source.extension.vsixmanifest
Labels: Type: bug, VS2022

#663 Fix VS2022 manifest file
  VisualStudio.Extension-2022/source.extension.vsixmanifest
Labels: Area: Config-and-Build

#664 Fix changelog generator job
  azure-pipelines.yml
Labels: Area: Config-and-Build

#665 Improve pipeline to build VS2019 and VS2022 in separate jobs
  azure-pipelines.yml
Labels: Area: Config-and-Build

#666 Change ID for VS2022 extension
  CSharp.BlankApplication/CS.BlankApplication-vs2022.vstemplate
  CSharp.ClassLibrary/CS.ClassLibrary-vs2022.vstemplate
  CSharp.TestApplication/CS.TestApplication-vs2022.vstemplate
  README.md
  VisualStudio.Extension-2022/source.extension.vsixmanifest
Labels: Area: Config-and-Build

#669 Improve output details for deploy and debug launch providers
  vs-extension.shared/DebugLauncher/NanoDebuggerLaunchProvider.cs
  vs-extension.shared/DeployProvider/DeployProvider.cs
Labels: Type: enhancement

#670 Work CI-CD
  azure-pipelines.yml
  nanoFramework.Tools.VisualStudio.sln
Labels: Area: Config-and-Build

#671 Improvements in debug client instantiation
  vs-extension.shared/NanoDeviceCommService/NanoDeviceCommService.cs
Labels: Type: enhancement, VS2019, VS2022
