Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2022-12, with the labels that each got.

#755 Fix .runsettings in Unit Test project template
  CSharp.TestApplication/.runsettings
  CSharp.TestApplication/NFUnitTest.nfproj
Labels: VS2019, VS2022, Type: Project Tempates

#757 Improve async package init
  VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  VisualStudio.Extension-2022/NanoFrameworkPackage.cs
  vs-extension.shared/MessageCentre/MessageCentre.cs
  vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
  vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: enhancement, VS2019, VS2022

#758 Improve showing Network Configuration dialog
  vs-extension.shared/ToolWindow.DeviceExplorer/DeviceExplorerCommand.cs
Labels: Type: bug, VS2019, VS2022

#759 Improvements in virtual device management
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml
  VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  vs-extension.shared/NanoDeviceCommService/NanoDeviceCommService.cs
  vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: bug, Type: enhancement, VS2019, VS2022

#761 Improvements in UI responsiveness with virtual device operation
  VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  VisualStudio.Extension-2022/NanoFrameworkPackage.cs
  VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: enhancement, VS2019, VS2022

#762 Improve virtual device shutdown and restart
  VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  VisualStudio.Extension-2022/NanoFrameworkPackage.cs
  vs-extension.shared/DeployProvider/DeployProvider.cs
  vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: enhancement, VS2019, VS2022

#763 Improvements in starting virtual device
  vs-extension.shared/DeployProvider/DeployProvider.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: enhancement, VS2019, VS2022
