Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2022-08, with the labels that each got.

#729 Fix parsing embedded bitmap resources
  Tools.BuildTasks-2019/ProcessResourceFiles.cs
Labels: Type: bug, VS2019, VS2022

#736 Update dependencies for VS17.3
  VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
  VisualStudio.Extension-2022/packages.lock.json
  VisualStudio.Extension-2022/source.extension.vsixmanifest
Labels: Type: dependencies, VS2022

#735 Add CommandLineArgsForDesignTimeEvaluation property to project system
  VisualStudio.Extension-2022/Rules/general.xaml
  VisualStudio.Extension-2022/Targets/NFProjectSystem.CSharp.targets
Labels: Type: bug, VS2022
