Repository nanoframework/nf-Visual-Studio-extension, pull requests merged in 2023-05, with the labels that each got.

#793 Add support for loading local nanoCLR instance in virtual device
  VisualStudio.Extension-2019/NanoFrameworkPackage.cs
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml
  VisualStudio.Extension-2019/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  VisualStudio.Extension-2022/NanoFrameworkPackage.cs
  VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml
  VisualStudio.Extension-2022/ToolWindow.DeviceExplorer/SettingsDialog.xaml.cs
  VisualStudio.Extension-2022/VisualStudio.Extension-vs2022.csproj
  vs-extension.shared/VirtualDeviceService/IVirtualDeviceService.cs
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: enhancement, VS2019, VS2022

#794 Fix spelling error
  vs-extension.shared/VirtualDeviceService/VirtualDeviceService.cs
Labels: Type: documentation, VS2019, VS2022

#802 Rework ByteEnumToItemsSource
  VisualStudio.Extension-2019/packages.lock.json
  VisualStudio.Extension-2022/packages.lock.json
  vs-extension.shared/Utilities/EnumToItemsSource.cs
Labels: Type: enhancement, Type: dependencies, VS2019, VS2022, CI: SKIP BUILD
